select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select gender , SUM(purchase_amount) as Revenue
from customer 
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id 
from customer 
where discount_appli

--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating) AS review
FROM customer
GROUP BY item_purchased	
ORDER BY review DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, AVG(purchase_amount) AS average_spend
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, 
       AVG(purchase_amount) AS average_spend, 
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment
with customer_type as (
	select customer_id , previous_purchases, 
	Case 
		When previous_purchases = 1 then 'New'
		When previous_purchases BETWEEN 2 AND 5 then 'Returning'
		Else 'Loyal'
		End as customer_segment
from customer
)

select customer_segment , count(*) as "Number of Customers"
from customer_type
group by customer_segment


-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category , item_purchased,
count(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id) DESC ) as item_rank
from customer
group by category, item_purchased
)

select item_rank ,category , item_purchased , total_orders
from item_counts
where item_rank<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(*)
from customer
where (previous_purchases > 5 )= (subsciption_status = 'Yes')